name: 'issue-task-parser'
description: 'Parse and return tasks contained in a specific issue.'
author: 'TakahashiIkki'

# Define your inputs here.
inputs:
  owner:
    required: true
    description:
      The account owner of the repository. The name is not case sensitive.

  repo:
    required: true
    description:
      The name of the repository without the .git extension. The name is not
      case sensitive.

  issue_number:
    required: true
    description: The number that identifies the issue.

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
